export const siteConfig = {
  name: "Venturis Realtors",
  tagline: "Elevating Real Estate to an Art Form",
  description: "Discover world-class luxury properties with Venturis Realtors. Expert guidance for buying, selling, and investing in premium real estate.",
  url: "https://venturisrealtors.com",
  ogImage: "/images/og.jpg",
  email: "hello@venturisrealtors.com",
  phone: "+1 (555) 123-4567",
  whatsapp: "+15551234567",
  address: "789 Luxury Avenue, Suite 1200, Beverly Hills, CA 90210",
  social: {
    instagram: "https://instagram.com/venturisrealtors",
    facebook: "https://facebook.com/venturisrealtors",
    twitter: "https://twitter.com/venturisrealtors",
    linkedin: "https://linkedin.com/company/venturisrealtors",
    youtube: "https://youtube.com/@venturisrealtors",
  },
  officeHours: "Monday - Saturday: 9:00 AM - 8:00 PM",
};

export const stats = [
  { value: "500+", label: "Luxury Properties" },
  { value: "50+", label: "Expert Agents" },
  { value: "1000+", label: "Happy Clients" },
  { value: "15+", label: "Years Experience" },
];

export const services = [
  {
    icon: "Home",
    title: "Property Buying",
    description: "Find your dream luxury property with our personalized concierge service and exclusive listings.",
    features: ["Personal property matching", "Private viewings", "Negotiation expertise", "Legal support"],
  },
  {
    icon: "TrendingUp",
    title: "Property Selling",
    description: "Premium marketing strategy to showcase your property to qualified luxury buyers worldwide.",
    features: ["Professional photography", "Global marketing", "Staging consultation", "Market analysis"],
  },
  {
    icon: "BarChart3",
    title: "Investment Advisory",
    description: "Strategic real estate investment guidance with comprehensive market intelligence and analytics.",
    features: ["Portfolio analysis", "ROI forecasting", "Market research", "Risk assessment"],
  },
  {
    icon: "Building2",
    title: "Luxury Villas",
    description: "Curated collection of the world's most exceptional villas, estates, and private residences.",
    features: ["Beachfront estates", "Mountain retreats", "Urban penthouses", "Private islands"],
  },
  {
    icon: "Store",
    title: "Commercial Spaces",
    description: "Prime commercial properties for businesses seeking prestigious addresses and premium locations.",
    features: ["Retail spaces", "Office buildings", "Mixed-use developments", "Investment properties"],
  },
  {
    icon: "Shield",
    title: "Property Management",
    description: "White-glove property management services ensuring your investment maintains its value.",
    features: ["Tenant screening", "Maintenance", "Financial reporting", "24/7 support"],
  },
  {
    icon: "Key",
    title: "Rental Services",
    description: "Exclusive rental portfolio featuring the finest residences for short and long-term leases.",
    features: ["Luxury apartments", "Corporate housing", "Vacation rentals", "Concierge services"],
  },
  {
    icon: "Users",
    title: "Real Estate Consulting",
    description: "Expert guidance for developers, investors, and high-net-worth individuals in real estate.",
    features: ["Market entry strategy", "Due diligence", "Portfolio diversification", "Exit planning"],
  },
];

export const propertyTypes = [
  { value: "apartment", label: "Apartments" },
  { value: "villa", label: "Villas" },
  { value: "penthouse", label: "Penthouses" },
  { value: "commercial", label: "Commercial" },
  { value: "office", label: "Offices" },
  { value: "land", label: "Land" },
];

export const amenitiesList = [
  "Swimming Pool", "Gym", "Spa", "Garden", "Parking", "Security", "Concierge",
  "Elevator", "Balcony", "Terrace", "Roof Access", "Wine Cellar", "Home Theater",
  "Smart Home", "Air Conditioning", "Heating", "Fireplace", "Walk-in Closet",
  "Study Room", "Guest Room", "Maid Room", "Storage", "Laundry", "Pet Friendly",
  "Beach Access", "Lake View", "City View", "Mountain View", "Golf Course",
  "Tennis Court", "Infinity Pool", "Jacuzzi", "Sauna", "Steam Room",
];

export const faqs = [
  {
    q: "What makes Venturis Realtors different from other real estate agencies?",
    a: "Venturis Realtors offers a white-glove, concierge-level service tailored to high-net-worth individuals. We provide exclusive off-market listings, AI-powered property matching, and a dedicated team of luxury property specialists with decades of combined experience.",
  },
  {
    q: "How do I schedule a private viewing of a property?",
    a: "Simply navigate to the property page and click 'Schedule a Viewing,' or contact our concierge team directly via phone, email, or WhatsApp. We will arrange a private viewing at your convenience, with virtual tour options also available.",
  },
  {
    q: "Do you offer virtual tours for international buyers?",
    a: "Yes, all our luxury properties feature immersive 3D virtual tours and high-definition video walkthroughs, allowing international buyers to experience properties remotely with the same level of detail as an in-person visit.",
  },
  {
    q: "What is the process for selling my property through Venturis?",
    a: "Our process begins with a complimentary property valuation, followed by a customized marketing strategy including professional photography, staging consultation, global listing distribution, and targeted outreach to qualified buyers through our extensive network.",
  },
  {
    q: "Do you provide property management services?",
    a: "Absolutely. Our full-service property management division handles everything from tenant screening and lease agreements to maintenance, financial reporting, and 24/7 emergency support, ensuring your investment is well cared for.",
  },
  {
    q: "Can you help with real estate investment analysis?",
    a: "Yes, our investment advisory team provides comprehensive market analysis, ROI projections, risk assessment, and portfolio diversification strategies to help you make informed real estate investment decisions.",
  },
  {
    q: "What areas do you serve?",
    a: "We specialize in premier locations across Beverly Hills, Malibu, Manhattan, Miami, Aspen, Hamptons, and select international luxury markets including London, Dubai, Paris, and Singapore.",
  },
  {
    q: "How do I get started with buying a luxury property?",
    a: "Begin by creating a free account to save properties and set alerts. You can also schedule a consultation with one of our luxury property specialists who will learn your preferences and curate a personalized selection of properties.",
  },
];

export const blogCategories = [
  "Market Insights", "Investment Tips", "Luxury Living", "Interior Design",
  "Architecture", "Real Estate News", "Neighborhood Guides", "Property Law",
];

export const propertyData = [
  {
    id: "1",
    title: "Modern Beachfront Villa",
    slug: "modern-beachfront-villa",
    description: "An architectural masterpiece perched on the coastline, offering panoramic ocean views, infinity pool, and world-class amenities. This stunning villa features floor-to-ceiling windows, a private beach access, and meticulously landscaped gardens.",
    price: 12500000,
    currency: "USD",
    type: "villa",
    purpose: "buy",
    status: "available",
    bedrooms: 6,
    bathrooms: 7,
    area: 8500,
    areaUnit: "sqft",
    images: [
      "photo-1613490493576-7fde63acd811?q=80",
      "photo-1600596542815-ffad4c1539a9?q=80",
      "photo-1600585154340-be6161a56a0c?q=80",
    ],
    featuredImage: "photo-1613490493576-7fde63acd811?q=80",
    amenities: ["Swimming Pool", "Infinity Pool", "Spa", "Garden", "Parking", "Security", "Beach Access", "Home Theater", "Wine Cellar"],
    location: {
      address: "1 Ocean Drive",
      city: "Malibu",
      state: "California",
      country: "USA",
      zipCode: "90265",
      coordinates: { lat: 34.0259, lng: -118.7798 },
    },
    features: ["Ocean views from every room", "Private beach access", "Infinity edge pool", "Outdoor kitchen", "Smart home system", "Helipad"],
    yearBuilt: 2023,
    nearbyPlaces: [
      { name: "Malibu Beach", distance: "0.2 mi", type: "beach" },
      { name: "Nobu Malibu", distance: "1.5 mi", type: "restaurant" },
      { name: "Malibu Country Mart", distance: "2.0 mi", type: "shopping" },
    ],
    isFeatured: true,
    isLuxury: true,
    tags: ["beachfront", "luxury", "ocean-view", "pool"],
  },
  {
    id: "2",
    title: "Beverly Hills Penthouse",
    slug: "beverly-hills-penthouse",
    description: "Ultra-luxurious penthouse in the heart of Beverly Hills with panoramic city views, private rooftop terrace, and designer interiors by renowned architects.",
    price: 18500000,
    currency: "USD",
    type: "penthouse",
    purpose: "buy",
    status: "available",
    bedrooms: 4,
    bathrooms: 5,
    area: 6200,
    areaUnit: "sqft",
    images: [
      "photo-1600607687939-ce8a6c25118c?q=80",
      "photo-1600566753086-00f18fb4b3aa?q=80",
      "photo-1600573472556-5b0d5d0b9b6f?q=80",
    ],
    featuredImage: "photo-1600607687939-ce8a6c25118c?q=80",
    amenities: ["Rooftop Terrace", "Concierge", "Parking", "Gym", "Spa", "Security", "Elevator", "Wine Cellar"],
    location: {
      address: "1000 Wilshire Blvd",
      city: "Beverly Hills",
      state: "California",
      country: "USA",
      zipCode: "90210",
      coordinates: { lat: 34.0736, lng: -118.4004 },
    },
    features: ["360-degree city views", "Private elevator", "Terrace with infinity pool", "Designer kitchen", "Wine cellar", "Home automation"],
    yearBuilt: 2022,
    nearbyPlaces: [
      { name: "Rodeo Drive", distance: "0.5 mi", type: "shopping" },
      { name: "Beverly Hills Hotel", distance: "1.0 mi", type: "hotel" },
      { name: "The Beverly Center", distance: "1.5 mi", type: "shopping" },
    ],
    isFeatured: true,
    isLuxury: true,
    tags: ["penthouse", "city-view", "luxury", "rooftop"],
  },
  {
    id: "3",
    title: "Manhattan Luxury Apartment",
    slug: "manhattan-luxury-apartment",
    description: "Elegant full-floor apartment in Manhattan's most prestigious building with Central Park views, private terraces, and world-class building amenities.",
    price: 9500000,
    currency: "USD",
    type: "apartment",
    purpose: "buy",
    status: "available",
    bedrooms: 3,
    bathrooms: 3.5,
    area: 3800,
    areaUnit: "sqft",
    images: [
      "photo-1600607687644-0f8d6b2b5b5a?q=80",
      "photo-1600607687920-3f5c3c7c5b5a?q=80",
      "photo-1600607687939-ce8a6c25118c?q=80",
    ],
    featuredImage: "photo-1600607687644-0f8d6b2b5b5a?q=80",
    amenities: ["Concierge", "Doorman", "Gym", "Pool", "Parking", "Storage", "Pet Friendly"],
    location: {
      address: "15 Central Park West",
      city: "New York",
      state: "New York",
      country: "USA",
      zipCode: "10023",
      coordinates: { lat: 40.7697, lng: -73.9812 },
    },
    features: ["Central Park views", "Private terrace", "Chef's kitchen", "Marble bathrooms", "Walk-in closets", "White-glove service"],
    yearBuilt: 2020,
    nearbyPlaces: [
      { name: "Central Park", distance: "0.1 mi", type: "park" },
      { name: "Lincoln Center", distance: "0.5 mi", type: "culture" },
      { name: "Whole Foods", distance: "0.3 mi", type: "shopping" },
    ],
    isFeatured: true,
    isLuxury: true,
    tags: ["apartment", "city-view", "central-park", "luxury"],
  },
  {
    id: "4",
    title: "Miami Waterfront Mansion",
    slug: "miami-waterfront-mansion",
    description: "Magnificent waterfront mansion with private dock, resort-style pool, and breathtaking Biscayne Bay views. Every detail exudes luxury and sophistication.",
    price: 22000000,
    currency: "USD",
    type: "villa",
    purpose: "buy",
    status: "available",
    bedrooms: 7,
    bathrooms: 9,
    area: 12000,
    areaUnit: "sqft",
    images: [
      "photo-1600566753190-17f0baa2a6c3?q=80",
      "photo-1600585154340-be6161a56a0c?q=80",
      "photo-1600596542815-ffad4c1539a9?q=80",
    ],
    featuredImage: "photo-1600566753190-17f0baa2a6c3?q=80",
    amenities: ["Private Dock", "Pool", "Spa", "Home Theater", "Gym", "Wine Cellar", "Tennis Court", "Garden"],
    location: {
      address: "50 Star Island Drive",
      city: "Miami",
      state: "Florida",
      country: "USA",
      zipCode: "33139",
      coordinates: { lat: 25.7814, lng: -80.1470 },
    },
    features: ["Biscayne Bay frontage", "Private dock for 100ft yacht", "Resort-style pool", "Outdoor entertainment area", "Smart home", "Staff quarters"],
    yearBuilt: 2021,
    nearbyPlaces: [
      { name: "South Beach", distance: "3 mi", type: "beach" },
      { name: "Miami Design District", distance: "5 mi", type: "shopping" },
      { name: "Wynwood Walls", distance: "4 mi", type: "culture" },
    ],
    isFeatured: true,
    isLuxury: true,
    tags: ["waterfront", "mansion", "pool", "dock"],
  },
  {
    id: "5",
    title: "Aspen Mountain Retreat",
    slug: "aspen-mountain-retreat",
    description: "Exquisite mountain retreat with stunning slope-side access, rustic-modern design, and premium ski-in/ski-out location in Aspen's most exclusive enclave.",
    price: 15800000,
    currency: "USD",
    type: "villa",
    purpose: "buy",
    status: "available",
    bedrooms: 5,
    bathrooms: 6,
    area: 7200,
    areaUnit: "sqft",
    images: [
      "photo-1600585154340-be6161a56a0c?q=80",
      "photo-1600596542815-ffad4c1539a9?q=80",
      "photo-1613490493576-7fde63acd811?q=80",
    ],
    featuredImage: "photo-1600585154340-be6161a56a0c?q=80",
    amenities: ["Ski-in/Ski-out", "Hot Tub", "Fireplace", "Game Room", "Home Theater", "Wine Cellar", "Garage"],
    location: {
      address: "123 Aspen Mountain Road",
      city: "Aspen",
      state: "Colorado",
      country: "USA",
      zipCode: "81611",
      coordinates: { lat: 39.1911, lng: -106.8175 },
    },
    features: ["Ski-in/ski-out access", "Stone fireplace", "Outdoor hot tub", "Mountain views", "Private balcony", "Heated driveway"],
    yearBuilt: 2022,
    nearbyPlaces: [
      { name: "Aspen Mountain", distance: "0.1 mi", type: "ski" },
      { name: "Downtown Aspen", distance: "1.5 mi", type: "city" },
      { name: "Aspen Airport", distance: "4 mi", type: "transport" },
    ],
    isFeatured: false,
    isLuxury: true,
    tags: ["mountain", "ski", "retreat", "luxury"],
  },
  {
    id: "6",
    title: "Dubai Palm Jumeirah Villa",
    slug: "dubai-palm-jumeirah-villa",
    description: "Spectacular beachfront villa on Palm Jumeirah with Arabian Gulf views, private beach, and ultra-modern Middle Eastern inspired architecture.",
    price: 30000000,
    currency: "USD",
    type: "villa",
    purpose: "buy",
    status: "available",
    bedrooms: 8,
    bathrooms: 10,
    area: 15000,
    areaUnit: "sqft",
    images: [
      "photo-1600596542815-ffad4c1539a9?q=80",
      "photo-1613490493576-7fde63acd811?q=80",
      "photo-1600566753190-17f0baa2a6c3?q=80",
    ],
    featuredImage: "photo-1600596542815-ffad4c1539a9?q=80",
    amenities: ["Private Beach", "Infinity Pool", "Spa", "Home Theater", "Gym", "Tennis Court", "Private Cinema", "Helipad"],
    location: {
      address: "Palm Jumeirah Frond G",
      city: "Dubai",
      state: "Dubai",
      country: "UAE",
      zipCode: "00000",
      coordinates: { lat: 25.1124, lng: 55.1390 },
    },
    features: ["Arabian Gulf frontage", "Private beach", "Infinity pool", "Outdoor lounge", "Imported marble finishes", "Smart home system"],
    yearBuilt: 2023,
    nearbyPlaces: [
      { name: "Atlantis The Palm", distance: "1 mi", type: "hotel" },
      { name: "Nakheel Mall", distance: "2 mi", type: "shopping" },
      { name: "Dubai Marina", distance: "5 mi", type: "city" },
    ],
    isFeatured: true,
    isLuxury: true,
    tags: ["dubai", "palm", "beachfront", "luxury"],
  },
];

export const agentsData = [
  {
    id: "1",
    name: "Isabella Venturis",
    slug: "isabella-venturis",
    title: "Founder & CEO",
    email: "isabella@venturisrealtors.com",
    phone: "+1 (555) 100-2000",
    whatsapp: "+15551002000",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=500&fit=crop&crop=face",
    bio: "With over 20 years in luxury real estate, Isabella founded Venturis Realtors with a vision to redefine the property experience. Her expertise spans international markets and ultra-high-net-worth clientele.",
    specialties: ["Luxury Villas", "International Properties", "Investment Portfolios"],
    socialLinks: [
      { platform: "linkedin", url: "#" },
      { platform: "twitter", url: "#" },
      { platform: "instagram", url: "#" },
    ],
    rating: 5.0,
    reviewCount: 128,
    isFeatured: true,
  },
  {
    id: "2",
    name: "Alexander Brooks",
    slug: "alexander-brooks",
    title: "Senior Partner, Luxury Estates",
    email: "alexander@venturisrealtors.com",
    phone: "+1 (555) 100-2001",
    whatsapp: "+15551002001",
    image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=500&fit=crop&crop=face",
    bio: "Alexander brings 15 years of experience in luxury estate sales and has closed over $2 billion in transactions. He specializes in Beverly Hills and Bel Air properties.",
    specialties: ["Beverly Hills", "Bel Air", "Estate Sales", "Luxury Penthouses"],
    socialLinks: [
      { platform: "linkedin", url: "#" },
      { platform: "twitter", url: "#" },
    ],
    rating: 4.9,
    reviewCount: 95,
    isFeatured: true,
  },
  {
    id: "3",
    name: "Sophia Chen",
    slug: "sophia-chen",
    title: "Director, International Markets",
    email: "sophia@venturisrealtors.com",
    phone: "+1 (555) 100-2002",
    whatsapp: "+15551002002",
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=500&fit=crop&crop=face",
    bio: "Sophia specializes in cross-border transactions with deep expertise in Asian and European luxury markets. Fluent in Mandarin, Cantonese, and French.",
    specialties: ["International Markets", "Asia Pacific", "Europe", "New Developments"],
    socialLinks: [
      { platform: "linkedin", url: "#" },
      { platform: "instagram", url: "#" },
    ],
    rating: 4.8,
    reviewCount: 76,
    isFeatured: true,
  },
  {
    id: "4",
    name: "Marcus Williams",
    slug: "marcus-williams",
    title: "Head of Commercial Real Estate",
    email: "marcus@venturisrealtors.com",
    phone: "+1 (555) 100-2003",
    whatsapp: "+15551002003",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=500&fit=crop&crop=face",
    bio: "Marcus leads our commercial division with expertise in office buildings, retail spaces, and mixed-use developments. His portfolio spans major US markets.",
    specialties: ["Commercial", "Office Buildings", "Retail", "Mixed-Use"],
    socialLinks: [
      { platform: "linkedin", url: "#" },
      { platform: "twitter", url: "#" },
    ],
    rating: 4.9,
    reviewCount: 63,
    isFeatured: false,
  },
  {
    id: "5",
    name: "Victoria Hart",
    slug: "victoria-hart",
    title: "Luxury Property Specialist",
    email: "victoria@venturisrealtors.com",
    phone: "+1 (555) 100-2004",
    whatsapp: "+15551002004",
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400&h=500&fit=crop&crop=face",
    bio: "Victoria's passion for architecture and design makes her the ideal agent for clients seeking extraordinary properties with独特 architectural significance.",
    specialties: ["Architectural Homes", "Interior Design", "Waterfront Properties"],
    socialLinks: [
      { platform: "instagram", url: "#" },
      { platform: "linkedin", url: "#" },
    ],
    rating: 4.7,
    reviewCount: 54,
    isFeatured: true,
  },
  {
    id: "6",
    name: "James O'Brien",
    slug: "james-obrien",
    title: "Investment Advisory Director",
    email: "james@venturisrealtors.com",
    phone: "+1 (555) 100-2005",
    whatsapp: "+15551002005",
    image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=500&fit=crop&crop=face",
    bio: "James provides strategic investment advisory services to institutional investors and high-net-worth individuals seeking optimal real estate portfolio allocation.",
    specialties: ["Investment Analysis", "Portfolio Management", "Market Research"],
    socialLinks: [
      { platform: "linkedin", url: "#" },
      { platform: "twitter", url: "#" },
    ],
    rating: 4.8,
    reviewCount: 42,
    isFeatured: false,
  },
];

export const testimonialsData = [
  {
    id: "1",
    clientName: "Robert & Elizabeth Kingsley",
    clientTitle: "Luxury Villa Buyers, Beverly Hills",
    clientImage: "https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=200&h=200&fit=crop&crop=face",
    content: "Venturis Realtors exceeded every expectation. They found us the perfect Beverly Hills estate and managed every detail of the acquisition with absolute professionalism. Truly a world-class experience.",
    rating: 5,
    propertyType: "Villa",
    isFeatured: true,
  },
  {
    id: "2",
    clientName: "Amanda Foster",
    clientTitle: "Penthouse Investor, Manhattan",
    clientImage: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&crop=face",
    content: "From initial consultation to closing, the Venturis team demonstrated an unparalleled understanding of the luxury market. Their AI-powered property matching saved me months of searching.",
    rating: 5,
    propertyType: "Penthouse",
    isFeatured: true,
  },
  {
    id: "3",
    clientName: "The Harrison Family",
    clientTitle: "Waterfront Estate Sellers, Miami",
    clientImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
    content: "Selling our Miami estate through Venturis was a seamless experience. Their marketing presentation was breathtaking, and they secured a sale above our asking price within two weeks.",
    rating: 5,
    propertyType: "Waterfront Estate",
    isFeatured: true,
  },
  {
    id: "4",
    clientName: "Dr. Sarah Mitchell",
    clientTitle: "Commercial Investor, Aspen",
    clientImage: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=face",
    content: "The investment advisory team at Venturis provided comprehensive market analysis and due diligence that gave me complete confidence in my commercial property investment. Exceptional service.",
    rating: 5,
    propertyType: "Commercial",
    isFeatured: false,
  },
  {
    id: "5",
    clientName: "James & Diana Wei",
    clientTitle: "International Buyers, Dubai",
    clientImage: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face",
    content: "As international buyers, we were initially concerned about the complexities of purchasing in Dubai. Venturis made the entire process transparent and effortless. We are now proud owners of a stunning Palm Jumeirah villa.",
    rating: 5,
    propertyType: "Villa",
    isFeatured: true,
  },
];

export const blogData = [
  {
    id: "1",
    title: "The Future of Luxury Real Estate: Trends Shaping 2026",
    slug: "future-luxury-real-estate-2026",
    excerpt: "Explore the transformative trends redefining luxury real estate, from AI-powered property matching to sustainable smart homes and experience-driven design.",
    content: "The luxury real estate market is undergoing a profound transformation in 2026. Artificial intelligence is revolutionizing how buyers discover properties, with algorithms that learn personal preferences and curate bespoke portfolios. Sustainable architecture has moved from trend to standard, with net-zero energy homes and biophilic design becoming hallmarks of true luxury. Smart home technology has evolved beyond convenience into predictive wellness systems that anticipate residents' needs.\n\nVirtual and augmented reality have eliminated geographical barriers, allowing international buyers to experience properties with remarkable fidelity. The definition of luxury has expanded to include wellness amenities, private outdoor spaces, and integrated technology. Properties that offer seamless indoor-outdoor living, dedicated wellness spaces, and advanced air and water purification systems command premium prices.\n\nThe rise of experience-driven design means luxury properties are being conceived as destinations unto themselves. Home theaters have evolved into private cinemas, wine cellars into tasting rooms, and home offices into executive suites with broadcast-quality video conferencing capabilities.",
    author: "Isabella Venturis",
    authorImage: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&h=100&fit=crop&crop=face",
    category: "Market Insights",
    tags: ["trends", "luxury", "2026", "market"],
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=500&fit=crop",
    readTime: 8,
    isFeatured: true,
    publishedAt: "2026-04-15",
  },
  {
    id: "2",
    title: "Investing in Ultra-Luxury Properties: A Strategic Guide",
    slug: "investing-ultra-luxury-properties-guide",
    excerpt: "A comprehensive guide to building and managing a luxury real estate portfolio, including market analysis, risk assessment, and wealth preservation strategies.",
    content: "Investing in ultra-luxury real estate requires a sophisticated approach that goes beyond traditional property investment metrics. The ultra-luxury segment operates differently from mainstream markets, with pricing influenced by scarcity, exclusivity, and intangible attributes rather than comparable sales alone.\n\nSuccessful investors in this space focus on several key strategies: geographic diversification across stable markets, acquiring properties with unique architectural significance, targeting developments in supply-constrained locations, and leveraging professional management to maintain asset values.\n\nRisk management is paramount. Due diligence must encompass title searches, zoning regulations, environmental assessments, and market absorption rates. The most successful ultra-luxury investors treat their real estate holdings as long-term wealth preservation vehicles rather than short-term trading assets.\n\nEmerging markets present compelling opportunities but require deeper local knowledge and stronger partnerships. Markets like Dubai, Singapore, and select European cities continue to attract global capital seeking safe havens.",
    author: "James O'Brien",
    authorImage: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&h=100&fit=crop&crop=face",
    category: "Investment Tips",
    tags: ["investment", "guide", "portfolio", "wealth"],
    image: "https://images.unsplash.com/photo-1560520653-9e0e4c89eb11?w=800&h=500&fit=crop",
    readTime: 12,
    isFeatured: true,
    publishedAt: "2026-03-28",
  },
  {
    id: "3",
    title: "Inside the World's Most Expensive Penthouses",
    slug: "worlds-most-expensive-penthouses",
    excerpt: "Take a virtual tour of the planet's most breathtaking penthouses, from Manhattan sky penthouses to Dubai's sky palaces. Discover what makes them truly priceless.",
    content: "The world's most expensive penthouses represent the pinnacle of architectural achievement and luxury living. These sky-high sanctuaries command views that stretch for miles and offer amenities that rival five-star hotels.\n\nAt the top of the market, penthouses in cities like New York, London, Hong Kong, and Dubai regularly trade for nine-figure sums. What justifies these extraordinary valuations? It is the combination of location, scarcity, design excellence, and the intangible prestige of owning a piece of the skyline.\n\nModern penthouse design has evolved dramatically. Today's offerings feature private rooftop infinity pools, personal fitness centers, wine cellars, home theaters, and staff quarters. The most exclusive properties offer private elevator access, 24-hour concierge services, and direct connections to luxury hotels.\n\nThe future of penthouse design points toward even greater personalization, with developers offering buyers the opportunity to work directly with world-renowned architects to customize every aspect of their residence.",
    author: "Alexander Brooks",
    authorImage: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&h=100&fit=crop&crop=face",
    category: "Luxury Living",
    tags: ["penthouses", "luxury", "architecture", "design"],
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=500&fit=crop",
    readTime: 10,
    isFeatured: true,
    publishedAt: "2026-03-15",
  },
  {
    id: "4",
    title: "Sustainable Luxury: Eco-Friendly Estate Design",
    slug: "sustainable-luxury-eco-friendly-estate",
    excerpt: "How the world's leading architects are blending sustainability with uncompromising luxury in the design of premium residential estates.",
    content: "The intersection of sustainability and luxury has created a new paradigm in high-end residential design. Today's discerning buyers demand properties that minimize environmental impact without sacrificing comfort or aesthetics.\n\nLeading architects are achieving this through passive house design principles, geothermal heating and cooling systems, solar integration, and sophisticated water management systems. Green roofs, living walls, and native landscaping reduce energy consumption while creating beautiful natural environments.\n\nSustainable luxury extends beyond the structure itself to encompass the entire lifestyle. Properties are being designed with electric vehicle charging stations, organic garden spaces, and systems that monitor and optimize energy usage in real time.\n\nThe financial case for sustainable luxury is compelling. These properties command premium prices, have lower operating costs, and appeal to a growing segment of environmentally conscious high-net-worth buyers.",
    author: "Sophia Chen",
    authorImage: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&h=100&fit=crop&crop=face",
    category: "Architecture",
    tags: ["sustainable", "eco-friendly", "design", "architecture"],
    image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=500&fit=crop",
    readTime: 7,
    isFeatured: false,
    publishedAt: "2026-02-20",
  },
  {
    id: "5",
    title: "Top 10 Neighborhoods for Luxury Living in 2026",
    slug: "top-neighborhoods-luxury-living-2026",
    excerpt: "Our experts reveal the most desirable luxury neighborhoods worldwide, from established enclaves to emerging hotspots for the ultra-wealthy.",
    content: "The geography of luxury living continues to evolve as wealthy buyers seek new destinations that offer security, amenities, and lifestyle alignment. Our experts have identified the top neighborhoods defining luxury living in 2026.\n\nBeverly Hills remains the gold standard for luxury living in Los Angeles, with its tree-lined streets, world-class shopping on Rodeo Drive, and architectural heritage. The Upper East Side of Manhattan continues to attract those seeking classic New York luxury with Central Park as their backyard.\n\nEmerging hotspots include Miami's Brickell Avenue corridor, where new ultra-luxury towers are redefining coastal living. Dubai's Palm Jumeirah and Emirates Hills remain premier destinations for international buyers seeking maximum value and minimum taxes.\n\nEuropean luxury neighborhoods like London's Mayfair, Paris's 16th Arrondissement, and Geneva's Cologny continue to attract global capital. In Asia, Singapore's Nassim Road and Hong Kong's Peak remain among the most expensive addresses on earth.",
    author: "Victoria Hart",
    authorImage: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=100&h=100&fit=crop&crop=face",
    category: "Neighborhood Guides",
    tags: ["neighborhoods", "luxury", "guide", "2026"],
    image: "https://images.unsplash.com/photo-1448630360428-6545e63d3f09?w=800&h=500&fit=crop",
    readTime: 9,
    isFeatured: false,
    publishedAt: "2026-02-10",
  },
  {
    id: "6",
    title: "Smart Home Technology in Luxury Real Estate",
    slug: "smart-home-technology-luxury-real-estate",
    excerpt: "The latest innovations in home automation and how they are transforming the luxury real estate market. From AI concierges to predictive maintenance.",
    content: "Smart home technology has become a defining feature of luxury properties, with systems that seamlessly integrate every aspect of the home environment. Today's smart homes go far beyond automated lighting and thermostats.\n\nArtificial intelligence serves as the brain of modern luxury homes, learning occupants' preferences for lighting, temperature, music, and security. Predictive maintenance systems monitor mechanical systems and alert homeowners to potential issues before they become problems.\n\nVoice control has evolved into conversational AI that can manage complex multi-step requests. Security systems now incorporate facial recognition, drone patrol integration, and biometric access controls. Home theaters transform into immersive entertainment spaces with automated blackout shades, projection systems, and acoustic optimization.\n\nThe most advanced properties feature health monitoring systems that track air quality, water purity, and even occupancy patterns to optimize energy usage while ensuring comfort.",
    author: "Isabella Venturis",
    authorImage: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&h=100&fit=crop&crop=face",
    category: "Real Estate News",
    tags: ["smart-home", "technology", "innovation", "automation"],
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=500&fit=crop",
    readTime: 6,
    isFeatured: false,
    publishedAt: "2026-01-25",
  },
];

export const galleryImages = [
  { src: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop", title: "Modern Villa Exterior", category: "Villas" },
  { src: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop", title: "Luxury Penthouse Living", category: "Penthouses" },
  { src: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop", title: "Beachfront Paradise", category: "Villas" },
  { src: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop", title: "Interior Elegance", category: "Interiors" },
  { src: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop", title: "Waterfront Estate", category: "Estates" },
  { src: "https://images.unsplash.com/photo-1600573472556-5b0d5d0b9b6f?w=800&h=600&fit=crop", title: "City Skyline View", category: "Penthouses" },
  { src: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop", title: "Minimalist Living Room", category: "Interiors" },
  { src: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&h=600&fit=crop", title: "Infinity Pool at Sunset", category: "Outdoor" },
  { src: "https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=800&h=600&fit=crop", title: "Luxury Kitchen Design", category: "Interiors" },
  { src: "https://images.unsplash.com/photo-1600566753086-00f18fb4b3aa?w=800&h=600&fit=crop", title: "Grand Foyer Entrance", category: "Interiors" },
  { src: "https://images.unsplash.com/photo-1600585152220-8d2f6c9e7f5e?w=800&h=600&fit=crop", title: "Spa Bathroom Retreat", category: "Interiors" },
  { src: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop", title: "Garden Landscape", category: "Outdoor" },
];

export const investmentPlans = [
  {
    id: "1",
    title: "Premium Real Estate Fund",
    description: "Diversified portfolio of luxury residential properties across prime global markets. Ideal for investors seeking stable long-term growth with moderate risk.",
    minInvestment: 500000,
    maxInvestment: 5000000,
    expectedROI: 12,
    duration: "5 Years",
    riskLevel: "Moderate",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=600&h=400&fit=crop",
    isActive: true,
  },
  {
    id: "2",
    title: "Luxury Development Partnership",
    description: "Co-invest in premium residential developments with top-tier architects and builders. High-growth potential in emerging luxury markets.",
    minInvestment: 1000000,
    maxInvestment: 10000000,
    expectedROI: 20,
    duration: "3 Years",
    riskLevel: "High",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&h=400&fit=crop",
    isActive: true,
  },
  {
    id: "3",
    title: "Commercial Property Trust",
    description: "Income-generating commercial real estate portfolio featuring premium office spaces and retail properties in major metropolitan areas.",
    minInvestment: 250000,
    maxInvestment: 3000000,
    expectedROI: 9,
    duration: "7 Years",
    riskLevel: "Low-Moderate",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&h=400&fit=crop",
    isActive: true,
  },
];
